services:
    db: 
        hostname: db
        image: ankane/pgvector
        ports:
            - 5432:5432
        restart: always
        environment:
            - POSTGRES_DB=vectordb
            - POSTGRES_USER=username
            - POSTGRES_PASSWORD=password
            - POSTGRES_HOST_AUTH_METHOD=trust
